Add Summarize Block
githubnext/blocks-examples pull request #41
Opened 2022-04-09 00:08 UTC by Wattenberger

This Block breaks a file into digestible chunks and summarizes them, using our fancy new OpenAI endpoint

![image](https://user-images.githubusercontent.com/3506269/162548282-9bad70d6-51c1-4475-ac41-40950b8b43d6.png)

2022-04-11 12:16 UTC, mattrothenberg requested changes
Dope! A few TS + a11y nits but this looks excellent

2022-04-11 12:16 UTC, mattrothenberg commented on src/blocks/folder-blocks/summarize/index.tsx
> +    useState<boolean>(isCollapsed);
`<boolean>` type specification isn't necessary, since we can infer this from the initial value )`isCollapsed` is a boolean)

2022-04-11 12:16 UTC, mattrothenberg commented on src/blocks/folder-blocks/summarize/index.tsx
> +    <div
Let's add `role="button"` or actually convert this to a button, if it's meant to be interactive.

2022-04-11 12:16 UTC, mattrothenberg commented on src/blocks/folder-blocks/summarize/index.tsx
> +  const [sections, setSections] = useState<any[]>([]);
Why `any[]`? Don't we have a type definition for a section further down in the file?

2022-04-11 17:46 UTC, mattrothenberg commented on src/blocks/file-blocks/summarize/index.tsx
> +    console.log(sections);
drop log

2022-04-11 17:46 UTC, mattrothenberg approved these changes

2022-04-11 17:58 UTC, merged

2022-04-12 18:40 UTC, jaked reviewed
missed this before, very cool

2022-04-12 18:40 UTC, jaked commented on src/blocks/file-blocks/summarize/index.tsx
> +      position[0] -= (match?.length || 0) + numberOfWhitespaces;
just curious, what's going on here?

2022-04-12 19:02 UTC, jaked commented on src/blocks/file-blocks/summarize/index.tsx
> +      position[0] -= (match?.length || 0) + numberOfWhitespaces;
ah got it got it makes sense